apiVersion: v1
kind: Service
metadata: 
  labels:
    app: stuff
  name: stuff-made-here
spec:
  ports:
    - name: expose-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: stuff
  type: NodePort
status:
  loadBalancer: {}